[package]
name = "sudoku"
version = "0.1.0"
authors = ["石博文 <sbw@sbw.so>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
libc = "*"
rand = "*"
bitflags = "*"

